name: Preview documentation PRs

on:
  pull_request:
    paths:
      - "docs/**"
      - "!docs/README.md"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORGANIZATION_ID }}
          vercel-project-id: ${{ secrets.VERCEL_DOCS_PROJECT_ID }} 
          github-comment: true
          working-directory: ./docs
          alias-domains: |
            preview.docs.lpadder.ml
            pr-{{PR_NUMBER}}.docs.lpadder.ml

