name: Deploy documentation

on:
  push:
    paths:
      - "docs/**"
      - "!docs/README.md"

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Vercel Deploy
        id: vercel-deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORGANIZATION_ID }}
          vercel-project-id: ${{ secrets.VERCEL_DOCS_PROJECT_ID }} 
          github-comment: false
          working-directory: "docs"
          vercel-args: "--prod"
