name: Build and deploy

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Vercel Deploy
        id: vercel-deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORGANIZATION_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} 
          github-comment: false
          vercel-args: "--prod"

      - name: Add deployment URL to GitHub Release
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/releases/{release_id}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_RELEASE_ID: ${{ github.event.release.id }}
          INPUT_BODY: |
            "Deployment URL: <${{ steps.vercel-deploy.outputs.preview-url }}>\n\n${{ github.event.release.body }}"

