name: Build and deploy

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Vercel Deploy
        id: vercel-deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORGANIZATION_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} 
          github-comment: false
          vercel-args: "--prod"

      - name: Create Vercel URL file
        run: echo ${{ steps.vercel-deploy.outputs.preview-url }} >> url.txt

      - name: Test output of the file
        run: cat url.txt

      - name: Upload to GitHub Releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: url.txt
          asset_name: url.txt
          asset_content_type: text/plain

